server:
  port: 8001
   
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.91.78.254:3306/warranty?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: D0llioU83

  http: 
    multipart: 
      maxFileSize: 20MB
      maxRequestSize: 20MB